# -*- coding: utf-8 -*-
"""projects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kg4KA6Wm45JMToMIkwmIzLtrIZ9H_TYq
"""

import random

# Welcome message
print("\n\tWelcome to My Number Guessing Game\n")

while True:
  randomNumber = random.randint(1,6)

  guessNumber = int(input("Guess a number between 1-6 : "))


  if guessNumber == randomNumber :
    print("\n\tCongratulation ! You guessed a number.\n")

    playAgain = str(input("Want to play more (Yes or No) ? ").lower())
    print("")
    if playAgain == "no" or playAgain == "n":
      break

  else :
    print("\n\tYou guess wrong number, the number is ", randomNumber,"\n")